baseURL = 'https://dragomirt.com/'
languageCode = 'en-US'
title = 'Dragomir Țurcanu ヽ(•‿•)ノ'
theme = 'hugo-bearblog'

defaultContentLanguage = "en"
# googleAnalytics = "G-RZ8GW0WK4L"

enableRobotsTXT = true

[ params ]

 # author = "dragomirt"
 # bio = "Software engineer and tech enthusiast"
 # description = "Software engineer and tech enthusiast"
 # enableRSS = false
 # enableComments = true
 # enableGoogleAnalytics = true
 #   showPowerBy = false
 #   showToc = true

 #   customCSS = [
 #       "css/custom.css"
 #       ]
  description = "Notes on software engineering, music, and the things I find interesting"
  title = "Dragomir Țurcanu ヽ(•‿•)ノ"
  hideMadeWithLine = true
  enablePostNavigator = true
  images = ["images/avatar.jpg"]
  favicon = "images/favicon.ico"


[ social ]
  # e.g.
#  gmail = "mailto:dtu@dragoimrt.com"
#  github = "https://github.com/dragomirt"
#  twitter = "https://twitter.com/dragomirturcanu"
#  linkedin = "https://www.linkedin.com/in/dragomirt/"
#   stackoverflow: your-github-link
  # facebook: your-facebook-link


[markup]
  [markup.highlight]
    style = 'dracula'
    lineNos = false
    codeFences = true
